version: '3.4'
name: mygarage
services:
  mygarage.api:
    container_name: mygarage.api
    image: ${DOCKER_REGISTRY-}mygarage-api:dev
    build:
      context: .
      dockerfile: MyGarage.API/Dockerfile
